theme: jekyll-theme-cayman
title: Mutex Monk
author:
  name:  Srinivas
  url:   https://bitbucket.com/srinivasvishal7
  email: srinivasvishal7@gmail.com
description: A personal blog about exploring the sciences of perception and cognition modeled into computers.
github:
  is_project_page: False
collections:
  tags:
    output: true
    permalink: tag/:path/