theme: jekyll-theme-cayman
title: Mutex Monk
author: Srinivas
tagline: A personal blog about my explorations on Computer Vision, Deep learning, Machine learning and Statistics
description: A personal blog about my explorations on Computer Vision, Deep learning, Machine learning and Statistics
github:
  is_project_page: True
